### ISSUE TITLE
Nicer go doc

### ISSUE THREAD

**Issue by oliverpool** [mochi-co/mqtt#112]
Congrats on the v2 release !

The go doc could look better, with the following improvements:
- link to https://pkg.go.dev/github.com/mochi-co/mqtt/v2 from the readme badge (it currently links to v1)
- add a newline between SPDX-Comment and `package` line to prevent is showing in the doc (see https://github.com/fluhus/godoc-tricks/blob/master/doc.go#L1-L5 for an example)

**Comment by mochi-co** [comment]
Thanks @oliverpool! I have implemented your suggestions as v2.0.2 - hopefully it fixes the issue once pkg.go.dev recaches.

**Comment by oliverpool** [comment]
👍🏼
https://github.com/mochi-co/mqtt/blob/v2.0.2/fanpool.go is still missing a newline

**Comment by mochi-co** [comment]
Ahh good catch! Should now be fixed, so I've issued the v2.0.2 release with these changes. I can't check locally right now but hopefully that resolves the remaining issue :)
