### ISSUE TITLE
Reopen #153 (Possible issue with Will retain flag)

### ISSUE THREAD

**Issue by dadebue** [mochi-co/mqtt#233]
### This is just a placeholder issue

From my experience the problem with LWT messages still exists. I've added details in #153.
Can you please reopen the issue #153? This issue can be deleted then...

BR
Marco

**Comment by dgduncan** [comment]
I have noticed the same thing so I am going to take a look at this when I get a moment.

**Comment by dgduncan** [comment]
@dadebue I opened up a PR that should resolve this issue.

**Comment by mochi-co** [comment]
Merged @dgduncan's PR and released as v2.2.12 - let me know if it resolves the issue :) Thanks for finding this!

**Comment by dadebue** [comment]
I can happily confirm that the issue is resolved! Thanks to everyone :)

**Comment by dgduncan** [comment]
@dadebue Glad to hear it! Let me know if you notice anything strange. I have a strong use case for LWT and retained LWT that has not been implemented yet so if problems still persist I would love to know :)
